package cn.enjoy.dao;

import cn.enjoy.model.EnjoyUser;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface EnjoyUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enjoy_user
     *
     * @mbggenerated Thu Sep 13 17:54:20 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enjoy_user
     *
     * @mbggenerated Thu Sep 13 17:54:20 CST 2018
     */
    int insert(EnjoyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enjoy_user
     *
     * @mbggenerated Thu Sep 13 17:54:20 CST 2018
     */
    int insertSelective(EnjoyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enjoy_user
     *
     * @mbggenerated Thu Sep 13 17:54:20 CST 2018
     */
    EnjoyUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enjoy_user
     *
     * @mbggenerated Thu Sep 13 17:54:20 CST 2018
     */
    int updateByPrimaryKeySelective(EnjoyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enjoy_user
     *
     * @mbggenerated Thu Sep 13 17:54:20 CST 2018
     */
    int updateByPrimaryKey(EnjoyUser record);

    EnjoyUser findUserByUsernameAndPwd(@Param("username") String username, @Param("passwd") String passwd);
}