package cn.enjoy.model;

public class EnjoyUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enjoy_user.id
     *
     * @mbggenerated Thu Sep 13 17:54:20 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enjoy_user.passwd
     *
     * @mbggenerated Thu Sep 13 17:54:20 CST 2018
     */
    private String passwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enjoy_user.username
     *
     * @mbggenerated Thu Sep 13 17:54:20 CST 2018
     */
    private String username;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enjoy_user.id
     *
     * @return the value of enjoy_user.id
     *
     * @mbggenerated Thu Sep 13 17:54:20 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enjoy_user.id
     *
     * @param id the value for enjoy_user.id
     *
     * @mbggenerated Thu Sep 13 17:54:20 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enjoy_user.passwd
     *
     * @return the value of enjoy_user.passwd
     *
     * @mbggenerated Thu Sep 13 17:54:20 CST 2018
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enjoy_user.passwd
     *
     * @param passwd the value for enjoy_user.passwd
     *
     * @mbggenerated Thu Sep 13 17:54:20 CST 2018
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd == null ? null : passwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enjoy_user.username
     *
     * @return the value of enjoy_user.username
     *
     * @mbggenerated Thu Sep 13 17:54:20 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enjoy_user.username
     *
     * @param username the value for enjoy_user.username
     *
     * @mbggenerated Thu Sep 13 17:54:20 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }
}